# Alacritty configuration file
# https://alacritty.org/config-alacritty.html

[window]
dimensions = { columns = 80, lines = 24 }
# Top-left corner
position = { x = 0, y = 0 } 
padding = { x = 10, y = 10 }
# MacOS only
decorations = "Buttonless" 
startup_mode = "Windowed"
# Make Option key behave as Alt
option_as_alt = "Both" 

[font]
normal = {family = "JetBrains Mono", style = "Regular"}
bold = {family = "JetBrains Mono", style = "Bold"}
italic = {family = "JetBrains Mono", style = "Italic"}
bold_italic = { family = "JetBrains Mono", style = "Bold Italic" }

# Github Dark Default Theme (https://github.com/projekt0n/github-theme-contrib/blob/main/themes/alacritty/github_dark_default.yml)
[colors]
primary = {background = "0x0d1117", foreground = "0xe6edf3"}
cursor = { text = "0x0d1117", cursor = "0xe6edf3" }
normal = { black = "0x484f58", red = "0xff7b72", green = "0x3fb950", yellow = "0xd29922", blue = "0x58a6ff", magenta = "0xbc8cff", cyan = "0x39c5cf", white = "0xb1bac4" }
bright = { black = "0x6e7681", red = "0xffa198", green = "0x56d364", yellow = "0xe3b341", blue = "0x79c0ff", magenta = "0xbc8cff", cyan = "0x39c5cf", white = "0xb1bac4" }

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "beam", blinking = "on" }

[terminal]
shell = { program = "/bin/zsh", args = ["-l"] }
osc52 = "CopyPaste"